// <auto-generated />
namespace TEDU.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class repair4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repair4));
        
        string IMigrationMetadata.Id
        {
            get { return "201606100032078_repair4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
